# Warning: this name must stay in sync with the badges referenced in the README
name: 'build Android 🤖'

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  android-build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        arch: [arm, aarch64]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt -y install ninja-build nasm

    - name: Build
      run: |
        ./configure.py --buildtype debug --debug-opts gl vk --host Android --host-arch ${{ matrix.arch }}
        make -f Makefile.Android.${{ matrix.arch }}
        . venv/bin/ngli-activate
        meson test -C builddir/Android/${{ matrix.arch }}/libnopegl

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: libnopegl-${{ matrix.arch }}
        path: builddir/Android/${{ matrix.arch }}
